[update] CEu v2.2.0
GTModpackTeam/gregtech-expert-2 pull request #125
Opened 2022-04-06 12:30 UTC by tier940

2022-04-06 16:09 UTC, Quarri6343 requested changes
oreがmetaitemになったことでどこかしら作れないアイテムが出てきているような気がします...

2022-04-07 01:54 UTC, tier940 commented
> oreがmetaitemになったことでどこかしら作れないアイテムが出てきているような気がします...

(作れないのは)ないです。無かったらエラー吐きます。
※逆に存在しないoreを指定してもエラー吐かない

2022-04-07 06:39 UTC, tier940 commented on overrides/config/gregtech.cfg
> +            B:nativeEUToFE=false
撤回します

2022-04-07 08:47 UTC, Quarri6343 approved these changes

2022-04-07 09:13 UTC, merged