[fix] Recipes that cannot be created
GTModpackTeam/gregtech-expert-2 pull request #143
Opened 2022-04-21 06:54 UTC by tier940

# New recipe
* Cable Anchor

# Fix recipes
* Network Tool
* Wireless Access Point
* Level Emitter
* Fluid Level Emitter
* Toggle Bus
* Inverted Toggle Bus

# Del recipes
* Certus Quartz Cutting Knife
* Nether Quartz Cutting Knife
* Certus Quartz Wrench
* Nether Quartz Wrench
* Color Applicator(refix)

2022-04-21 10:15 UTC, Quarri6343 requested changes

2022-04-21 10:15 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> -# Certus Quartz Cutting Knife
removeandhide出来ていない気がします

2022-04-21 10:15 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +# Level Emitter
既にprocessorの使用比というか消費バランスが崩壊しているのでもうちょっと改善できませんか
これ以上やるとAE2のcalculation processorの存在意義が消えてしまいます

2022-04-21 11:31 UTC, tier940 commented on overrides/scripts/normal/AppliedEnergistics.zs
> -# Certus Quartz Cutting Knife
tools.zsでやってるので心配不要

2022-04-21 11:40 UTC, tier940 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +# Level Emitter
確認したけど割と使ってた

2022-04-21 15:36 UTC, Quarri6343 reviewed
matrix coreを追加した時もうAE2のレシピはいじらないって約束したじゃないですか
随分とすぐ裏切りましたね...

2022-04-22 01:09 UTC, tier940 commented
> 

Cable Anchor以外なぜか作れなくなったレシピの再修正(現行レシピをCTで再設定)なので、そこだけ切り出します。

2022-04-22 04:11 UTC, Quarri6343 approved these changes
お手数おかけしました

2022-04-22 04:15 UTC, merged