[add] AE2 assembler recipes
GTModpackTeam/gregtech-expert-2 pull request #154
Opened 2022-05-03 05:38 UTC by tier940

2022-05-03 05:41 UTC, tier940 commented
# Add recipes
## AE2
* Storage Housing
* Level Emitter
* Fluid Level Emitter
* Storage Bus
* Fluid Storage Bus
* OreDict Storage Bus
* Toggle Bus

## ExtraCells
* Fluid Housing
* Advanced Storage Housing

2022-05-03 06:34 UTC, Quarri6343 commented
組立器のレシピかぶりが怖いので後で動確します

2022-05-04 11:48 UTC, Quarri6343 requested changes

2022-05-04 11:48 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +    [<metaitem:plateSteel>, <metaitem:item_filter>, <metaitem:plateSteel>]
filterいらないです

2022-05-04 11:48 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +    .buildAndRegister();
このレシピにしてしまうとAE2解禁と同時に誰もが組立機を使うのでクラフトレシピが腐ります
電圧を上げるなりして対処が必要です

2022-05-04 11:48 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +    [<metaitem:plateStainlessSteel>, <metaitem:fluid_filter>, <metaitem:plateStainlessSteel>]
filterは2.0.0で追加してください...

2022-05-04 11:48 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +    .buildAndRegister();
同上です

2022-05-04 11:48 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedEnergistics.zs
> +    .buildAndRegister();
同上

2022-05-05 00:19 UTC, merged