[hotfix] v1.1.1
GTModpackTeam/gregtech-expert-2 pull request #73
Opened 2022-02-27 11:54 UTC by tier940

2022-02-27 14:23 UTC, Quarri6343 requested changes
全部拾い切れてるか自信がないのであとで実機で調べたいです

2022-02-27 14:23 UTC, Quarri6343 commented on CHANGELOG.md
> +* 2k Spatial Component
厳密には2^3k Spatial Component(初めてレビューするのでテスト)

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedenErgistics.zs
>          <ore:plateTungstenSteel> * 4,
EV circuitを使うならplateTitaniumの方がいいと思います

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedenErgistics.zs
>      .fluidInputs(<liquid:tungsten_steel> * 144)
ここをタングステンスチールにしてしまうとEVで作るのがきつくなります

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/AppliedenErgistics.zs
>          <ore:plateNeutronium> * 4,
ここをニュートロニウムにするとLuVで作れなくなります

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/GregTech.zs
> +        <metaitem:dustTinyNetherQuartz>
ネザークォーツが0.5から0.66に増殖しています
Pure Nether Quartz Crystal=Nether Quartz*0.5
↓
stickNetherQuartz=Nether Quartz*0.5
dustTinyNetherQuartz=Nether Quartz*0.11

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/GregTech.zs
> +        <metaitem:dustTinyCertusQuartz> * 2
上と同様に増殖しています

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/GregTech.zs
>      .EUt(2)
ここはHVに戻すかfluix crystalと統合して30EU/tのどちらかにした方がいいかと

2022-02-27 14:23 UTC, Quarri6343 commented on overrides/scripts/normal/GregTech.zs
> +    .fluidInputs([<liquid:distilled_water> * 144])
蒸留水は金属ではないので144の倍数でなくていいです

2022-02-27 15:15 UTC, tier940 commented on overrides/scripts/normal/GregTech.zs
> +    .fluidInputs([<liquid:distilled_water> * 144])
50に戻しました

2022-02-27 15:17 UTC, tier940 commented on overrides/scripts/normal/AppliedenErgistics.zs
>      .fluidInputs(<liquid:tungsten_steel> * 144)
HSLA Steelに更新しました

2022-02-27 15:20 UTC, tier940 commented on overrides/scripts/normal/GregTech.zs
> +        <metaitem:dustTinyNetherQuartz>
今回追加したロッドは全てExtruderにすべて変更

2022-02-27 15:20 UTC, tier940 commented on overrides/scripts/normal/GregTech.zs
> +        <metaitem:dustTinyCertusQuartz> * 2
上と同じく

2022-02-27 15:21 UTC, tier940 commented on overrides/scripts/normal/GregTech.zs
>      .EUt(2)
30EU/tに更新しました

2022-02-27 15:22 UTC, tier940 commented on overrides/scripts/normal/AppliedenErgistics.zs
>          <ore:plateTungstenSteel> * 4,
チタニウムのプレートに変更しました

2022-02-27 15:23 UTC, tier940 commented on overrides/scripts/normal/AppliedenErgistics.zs
>          <ore:plateNeutronium> * 4,
すべてのコンポーネントに利用しているスチールを見直す必要がありそう

2022-02-28 07:02 UTC, tier940 commented
* Certus Quartz Plate
* Quartzite Plate
    * 時間とEU/tが違ったので訂正。

* Certus Quartz Rod
* Nether Quartz Rod
    * Pureで作成するレシピの訂正。

2022-02-28 07:19 UTC, Quarri6343 requested changes
コンポーネントのプレート周りを見直す必要がありそうです

2022-02-28 08:08 UTC, Quarri6343 commented
以下他に必要な変更点です
・Security TerminalをMEシステムを作った段階で作れるようにする
・Matrix CoreのレシピとFormation/Annihilation Coreのレシピ競合を回避する
・cable facadeのツールチップが表示されないのを修正
・capacity cardをcertus quartz crystalで作れるようにする
・Fluix Pearlの作成個数が逆になっているのを直す
・Network Visualization Toolのレシピ緩和
・UHVのエネルギーハッチ系列のレシピが壊れているのを修正

2022-02-28 09:16 UTC, Quarri6343 approved these changes
見た感じ問題なさそうです

2022-02-28 09:40 UTC, Quarri6343 commented
他に必要な変更点です
・コンポーネントのレシピ被りを解決
・Network Visualization Toolが同じコア2つで作れてしまう問題を修正(HVマグネットと同じ)

2022-02-28 09:48 UTC, Quarri6343 commented
・chemical bathでは塩素でAE2ケーブルを脱色しているのにクラフトでは水バケツで脱色できてしまう不具合を修正

2022-02-28 09:50 UTC, Quarri6343 commented
・クエストのv0.6.5にbugfixがあるのでマージの方よろしくお願いします

2022-02-28 10:56 UTC, Quarri6343 commented
・256kストレージコンポーネントと1024kとのレシピ被りを解決
・256k液体コンポーネントと1024kとのレシピ被りを解決
・https://github.com/GTModpackTeam/gregtech-expert-2/pull/73#issuecomment-1054075022
・Feral Flare Lanternのツールチップがメガトーチになっている

2022-02-28 12:32 UTC, Quarri6343 approved these changes
多分大丈夫でしょう

2022-02-28 12:32 UTC, merged