[update] AE2翻訳のたたき台
GTModpackTeam/gregtech-expert-2 pull request #77
Opened 2022-03-05 02:50 UTC by tier940

2022-03-05 04:08 UTC, Quarri6343 requested changes
craftingをクラフティングに統一したのは[これ](https://www.youtube.com/watch?v=N5JOLJdBNlU)を参考にしました

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.Controller.desc=コントローラを作る
MEコントローラを作る

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.P2P=ネットワークを示すポイント
ポイント・トゥー・ポイント・ネットワーク

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.Recursive.desc=ストレージバスのインターフェイスを設置する
ストレージバス上にインターフェイスを設置する

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.CraftingCPU.desc=クラフトユニットを作る
クラフティングユニットを作る

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.Facade.desc=外装パネルを作る
偽装板を作る

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.PortableCell.desc=ポータブルストレージを作る
ポータブルセルを作る

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/modpack/lang/en_us.lang
> +modpack.ae2.p2p_gtceu.tooltip.1=Made by right-clicking ME P2P Tunnel with a gregtech energy cable.
GregTech

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/modpack/lang/ja_jp.lang
> +modpack.ae2.p2p_gtceu.tooltip.1=Gregtechのケーブルを持ってME P2P Tunnelを右クリックすることで変化します。
GregTech

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/modpack/lang/ru_ru.lang
> +modpack.ae2.p2p_gtceu.tooltip.1=Made by right-clicking ME P2P Tunnel with a gregtech energy cable.
GregTech

2022-03-05 04:08 UTC, Quarri6343 commented on overrides/resources/modpack/lang/zh_cn.lang
> +modpack.ae2.p2p_gtceu.tooltip.1=Made by right-clicking ME P2P Tunnel with a gregtech energy cable.
GregTech

2022-03-05 10:41 UTC, tier940 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.TerminalStyle_Tall=最小化
コレは有ってる(GUIで見た)

2022-03-05 10:42 UTC, tier940 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.TerminalStyle_Tall=最小化
コレは有ってる(GUIで見た)

2022-03-05 10:42 UTC, tier940 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.TerminalStyle_Small=最大化
コレは有ってる(GUIで見た)

2022-03-05 10:51 UTC, tier940 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.appliedenergistics2.GTCEUTunnel=GTCEU
Modpackがまだ更新できないので居るけど、どうしようかな...

2022-03-06 04:07 UTC, Quarri6343 approved these changes
いつもありがとうございます

2022-03-06 04:07 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.TerminalStyle_Tall=最小化
了解です

2022-03-06 04:07 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.TerminalStyle_Small=最大化
了解です

2022-03-06 04:16 UTC, merged