Update #85
GTModpackTeam/gregtech-expert-2 pull request #90
Opened 2022-03-14 03:54 UTC by tier940

2022-03-14 04:38 UTC, Quarri6343 requested changes
よろしくお願いします

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +chat.appliedenergistics2.StationCanNotBeLocated=拠点の位置を見つけられません。
セキュリティーステーションのことならステーションでいいかと

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacement=ブロック配置について
プロック設置について

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacementYes=ブロックは設置させる
ブロックは設置される

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacementNo=ブロックはアイテムとしてドロップさせる
ブロックはアイテムとしてドロップされる

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.SchedulingMode=スケジュールモード
[スケジューリング](https://kotobank.jp/word/%E3%82%B9%E3%82%B1%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%B0-4891)モード

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.SchedulingModeDefault=ネットワークが空になるまで最初の項目をエクスポートし次の項目を試してください
ネットワークが空になるまで最初のアイテムを搬出してから次のアイテムに移る

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.SchedulingModeRoundRobin=総当たりにアイテムを書き出す
順番にアイテムを搬出する/ラウンドロビンモードで搬出する

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.SchedulingModeRandom=ランダムにアイテムを書き出す
ランダムにアイテムを搬出する

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.ItemsStored=格納アイテム: %s
在庫

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.ToggleShowFullInterfacesOffDesc=空きがあるインターフェースを表示
空きがあるインターフェースのみを表示

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.FreeMolecularSlotShortcutDesc=スロットが空いているインターフェースを切り替えて分子組立室をショートカット検索
スロットが空いているインターフェースを切り替えて分子組立室を検索するショートカット

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +commands.ae2.ChunkLogger=チャンクロードとアンロードに関するサーバーログへの書き込みを切替ます。
チャンクロードとアンロードに関するサーバーログへの書き込みを切り替えます。

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +commands.ae2.ChunkLoggerOn=チャンクロードを開始しました。
チャンクロギングを開始しました。
（チャンクロードではなさそう）

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +commands.ae2.ChunkLoggerOff=チャンクロードを終了しました。
チャンクロギングを終了しました。

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.CrystalGrowthAccelerator=加速機は控えめな表現
😠

2022-03-14 04:38 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.PortableCell=ストレージの遊牧民
別に遊牧している訳ではないので放浪者でしょう

2022-03-14 05:00 UTC, tier940 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacement=ブロック配置について
プロック？

2022-03-14 07:48 UTC, Quarri6343 requested changes
前回レビューできていないところがありました
すみません

2022-03-14 07:48 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacement=ブロック配置について
誤字でした

2022-03-14 07:48 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +gui.tooltips.appliedenergistics2.BlockPlacement=ブロック配置について
ブロック設置について

2022-03-14 07:48 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.CraftingTerminal=もっと大きなテーブル
もっと大きな作業台
原文のテーブルは多分省略形です...

2022-03-14 07:48 UTC, Quarri6343 commented on overrides/resources/appliedenergistics2/lang/ja_jp.lang
> +achievement.ae2.ChargedQuartz=衝撃的
ショッキング
原文は多分感電(ショック)の方の意味です
チャージドケルタスクォーツを見つけて心を痛める人はいないと思います

2022-03-17 08:13 UTC, tier940 reviewed
LGTM

2022-03-17 08:13 UTC, merged