Brushup #95
GTModpackTeam/gregtech-expert-2 pull request #96
Opened 2022-03-19 04:38 UTC by tier940

2022-03-21 15:48 UTC, Quarri6343 requested changes
いくつか気がかりだったのでマークしておきました

2022-03-22 06:59 UTC, tier940 commented on overrides/scripts/materials.zs
> +    ])
エラーするから故意にそうしてる

2022-03-22 08:18 UTC, tier940 commented on overrides/scripts/normal/EnderIO/02_Materials.zs
> +    ])
End Steel Dustだと鬼畜かなと思ったからEndstone Dustにしてた

2022-03-22 08:20 UTC, tier940 commented on overrides/scripts/normal/EnderIO/02_Materials.zs
> +        <ore:dustEnderPearl>
確かに。何か案ありますか...？

2022-03-22 09:01 UTC, Quarri6343 requested changes

2022-03-22 09:01 UTC, Quarri6343 commented on overrides/scripts/normal/EnderIO/02_Materials.zs
> +        <ore:dustEnderPearl>
shulker box dust? (shulker boxにレシピ追加)

2022-03-24 09:13 UTC, tier940 commented on overrides/scripts/materials.zs
> +    ])
作成と分解では入れたのでクローズ

2022-03-24 09:14 UTC, tier940 commented on overrides/scripts/normal/EnderIO/02_Materials.zs
> +        <ore:dustEnderPearl>
無理だったのでPlatinum Dustにしました

2022-03-25 09:11 UTC, Quarri6343 requested changes

2022-03-25 14:12 UTC, Quarri6343 approved these changes

2022-03-25 14:26 UTC, merged