[add] Enable EIO Generator
GTModpackTeam/gregtech-expert-2 pull request #99
Opened 2022-03-20 01:53 UTC by tier940

2022-03-20 15:25 UTC, Quarri6343 requested changes
チャージャー以外は見直した方がいいと思います

2022-03-20 15:25 UTC, Quarri6343 commented on overrides/scripts/normal/EnderIO/05_Conduits.zs
> +    .buildAndRegister();
HVでGTEUのP2Pが解禁されるので、
小回りが利くケーブルはともかく高価なエネルギーコンジット系統はどれも解禁された時点で淘汰されています

2022-03-21 14:29 UTC, tier940 commented
@Quarri6343 
一応で言うけどGTEU->FEへのケーブル変換のcfg切る+チャージャーRFアイテムを対象外って忘れてない？

2022-03-21 14:30 UTC, tier940 commented on overrides/scripts/normal/EnderIO/05_Conduits.zs
> +    .buildAndRegister();
使いたい人は使うって説明したはず

2022-03-21 14:40 UTC, Quarri6343 commented on overrides/scripts/normal/EnderIO/05_Conduits.zs
> +    .buildAndRegister();
分かりました

2022-03-21 15:18 UTC, Quarri6343 requested changes
stellar capacitorで再レビューしました

2022-03-21 15:18 UTC, Quarri6343 commented on overrides/scripts/normal/EnderIO/00_Machines.zs
> +]);
<再レビュー>
解禁：HV(512EU/t)
使用可能なキャパシタ：Stellar Capacitor(LuV, 32768EU/t)
出力：180EU/t
産廃です
これを使いたいと思う人は流石に地球上に存在しないと思います...

2022-03-21 15:18 UTC, Quarri6343 commented on overrides/scripts/normal/EnderIO/05_Conduits.zs
> +assembler.recipeBuilder()
Enhan**ce**d Energy Conduit

2022-03-21 15:20 UTC, Quarri6343 commented
`一応で言うけどGTEU->FEへのケーブル変換のcfg切る+チャージャーRFアイテムを対象外って忘れてない？`

変換器(等倍)を挟む前提でレビューを行いました

2022-03-21 16:11 UTC, Quarri6343 commented
やっぱりsimple generatorも消しませんか
煙を出す発電機として今後cleanroomの中にねじ込まれたら、発電機を持ち込めないゲームバランスと無菌室という世界観が壊れます
(昨日GTCEuのdevと相談しましたがcleanroom側でsimpleを無効化することは不可能です)

2022-03-21 16:12 UTC, tier940 commented
そうだ、その話を忘れてた。
そうなるとEIOの発電機全部死亡じゃん。

2022-03-21 16:16 UTC, closed without merging